services:
    database:
        image: mongo:6-jammy
        container_name: socketio-chat-db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - "mongo-data:/data/db"
            - "mongo-config:/data/configdb"
        networks:
            - app-network
        restart: unless-stopped

    web:
        container_name: socketio-chat-app
        image: ${DOCKERHUB_USERNAME}/socketio-chat-app:latest
        depends_on:
            - database
        ports:
            - "127.0.0.1:${APP_PORT}:${APP_PORT}"
        networks:
            - app-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:${APP_PORT}/health-check || exit 1"]
            retries: 3
            interval: 30s
            timeout: 10s
            start_period: 30s
        env_file:
            - .env
networks:
    app-network:
        driver: bridge
        name: socketio-chat-network

volumes:
    mongo-data:
        name: socketio-chat-mongo-data
    mongo-config:
        name: socketio-chat-mongo-config