services:
    socketio-chat-app-db:
        image: mongo:6-jammy
        container_name: socketio-chat-app-db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - "socketio-chat-app-mongo-data:/data/db"
            - "socketio-chat-app-mongo-config:/data/configdb"
        networks:
            - socketio-chat-app-network
        restart: unless-stopped

    socketio-chat-app:
        container_name: socketio-chat-app
        image: ${DOCKERHUB_USERNAME}/socketio-chat-app:latest
        depends_on:
            - socketio-chat-app-db
        ports:
            - "127.0.0.1:${APP_PORT}:${APP_PORT}"
        networks:
            - socketio-chat-app-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:${APP_PORT}/health-check || exit 1"]
            retries: 3
            interval: 30s
            timeout: 10s
            start_period: 30s
        env_file:
            - .env
networks:
    socketio-chat-app-network:
        driver: bridge
        name: socketio-chat-app-network

volumes:
    socketio-chat-app-mongo-data:
        name: socketio-chat-app-mongo-data
    socketio-chat-app-mongo-config:
        name: socketio-chat-app-mongo-config