services:
    chat-app-db:
        image: mongo:7.0.25-jammy
        container_name: chat-app-db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - "chat-app-mongo-data:/data/db"
        networks:
            - chat-app-network
        restart: unless-stopped

    chat-app:
        container_name: chat-app
        image: ${DOCKERHUB_USERNAME}/chat-app:latest
        depends_on:
            - chat-app-db
        ports:
            - "${APP_HOST}:${APP_PORT}:${APP_PORT}"
        networks:
            - chat-app-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://chat-app:${APP_PORT}/health-check"]
            retries: 3
            interval: 30s
            timeout: 10s
            start_period: 30s
        env_file:
            - .env
networks:
    chat-app-network:
        driver: bridge

volumes:
    chat-app-mongo-data:
        name: chat-app-mongo-data